from . import combined_invoice
from . import res_users
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import product_template
from . import account_move
from . import stock_picking
from . import stock_move
from . import stock_location
from . import product_template_buyer_info
from . import purchase_order
from . import stock_warehouse
from . import hr_employee
from . import mrp_bom
