# -*- coding: utf-8 -*-

import logging

from odoo import fields, models

_logger = logging.getLogger(__name__)


class MrpProduction(models.Model):
    _inherit = "mrp.production"

    dv_fix_valuation_to_standard_price = fields.Boolean(
        string="Fix valuation to Standard Price",
        help="When enabled: raw/component lines use Standard Price × quantity; the main finished "
        "product is valued at the sum of those component SVL amounts (material cost total).",
        copy=False,
    )

    def _dv_get_moves_for_valuation_fix(self):
        """Return all done stock moves generated by this MO.

        Uses both functional and technical one2many fields to avoid missing finished moves
        in edge cases (backorders, byproducts, manual edits).
        """
        self.ensure_one()
        moves = (
            self.move_raw_ids
            | self.move_finished_ids
            | self.move_byproduct_ids
            | self.all_move_raw_ids
            | self.all_move_ids
        ).exists()
        done_moves = moves.filtered(lambda m: m.state == "done" and not m.scrapped)
        for m in done_moves:
            if m.production_id == self and m.product_id == self.product_id:
                kind = "finished"
            elif m.production_id == self:
                kind = "byproduct"
            elif m.raw_material_production_id == self:
                kind = "raw"
            else:
                kind = "other"
            _logger.info(
                "dv_mrp_moves mo=%s id=%s move_id=%s product=%s kind=%s valuation=%s "
                "svl_count=%s am_ids=%s",
                self.name,
                self.id,
                m.id,
                m.product_id.display_name,
                kind,
                m.product_id.valuation,
                len(m.stock_valuation_layer_ids),
                m.account_move_ids.ids,
            )
        return done_moves

    def action_dv_apply_standard_price_valuation_fix(self):
        for mo in self:
            mo.dv_fix_valuation_to_standard_price = True
            if mo.state == "done":
                fix_moves = mo._dv_get_moves_for_valuation_fix()
                _logger.info(
                    "dv_mrp_action_fix mo=%s id=%s fix_move_ids=%s",
                    mo.name,
                    mo.id,
                    fix_moves.ids,
                )
                fix_moves._dv_fix_mrp_valuation_to_standard_price()
        return True

    def _post_inventory(self, cancel_backorder=False):
        """Run fix right after stock moves are posted (same moment as core MO completion).

        Note: core ``button_mark_done`` calls ``_post_inventory`` *before* setting MO state to
        ``done``, so checking ``state == 'done'`` here would skip the fix every time.
        """
        res = super()._post_inventory(cancel_backorder=cancel_backorder)
        for mo in self.exists():
            if mo.dv_fix_valuation_to_standard_price:
                fix_moves = mo._dv_get_moves_for_valuation_fix()
                _logger.info(
                    "dv_mrp_post_inventory mo=%s id=%s state=%s fix_move_ids=%s",
                    mo.name,
                    mo.id,
                    mo.state,
                    fix_moves.ids,
                )
                fix_moves._dv_fix_mrp_valuation_to_standard_price()
        return res

    def button_mark_done(self):
        # Fix runs from ``_post_inventory`` (called inside ``super()``) once moves are done.
        return super().button_mark_done()

